# fly.toml app configuration file generated for good-face-bad-face on 2024-01-17T17:09:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "good-face-bad-face"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 9001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
